on:
  workflow_call:
    inputs:
      ponyhof:
        type: string
        description: Some other variable for the job.
jobs:
  jobB:
    needs: jobA
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.0
      - uses: actions/download-artifact@v4.1.0
        with:
          name: jobA
      - run: echo "${{ inputs.ponyhof }}"
      - run: ls -la
